[package]
name = "curl-bash-attack"
version = "0.1.0"
description = "Server-side detection of using bash | curl in the CLI."
edition = "2024"
repository = "https://github.com/m4tx/curl-bash-attack.git"
homepage = "https://github.com/m4tx/curl-bash-attack"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1"
async-stream = "0.3"
bytes = "1"
chrono = "0.4"
cot = { version = "0.2", default-features = false }
statrs = "0.18"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
